name: project_RobotX_build

on:
  # Triggered whenever push to the main branch
  push:
    branches: [ "main" ]

  # Triggered whenever a pull request is created on main
  pull_request:
    branches: [ "main" ]
    types: [ opened ]

jobs:
  build:
    # Create a container on the last version of Ubuntu
    runs-on: ubuntu-latest

    steps:
    
    - name: Make sure locale supports UTF-8
      run: |
        sudo apt update && sudo apt install locales
        sudo locale-gen en_US en_US.UTF-8
        sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
        export LANG=en_US.UTF-8

    - name: Setup sources
      run: |        
        sudo apt install -y software-properties-common
        sudo add-apt-repository universe

    - name: Add ROS2 GPG key
      run: |
        sudo apt update && sudo apt install curl -y
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

    - name: Add repository to sources list
      run: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

    - name: Install ROS2 packages
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install ros-humble-desktop
        sudo apt install ros-dev-tools

    - name: Setup workspace
      run: |
          source /opt/ros/humble/setup.bash
          mkdir robotx_ws
          cd robotx_ws
      # We want to use GitHub CI checkout version 3 for checking out the branch
    - uses: actions/checkout@v3
      with:
          path: ros_ws/
          
    - name: Build project
      run: |
          colcon build
          source install/setup.bash
          
