
name: ROS 2 CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_ROBOTX }}

    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive' # This will now work because the SSH agent is set up

    - name: Set up ROS
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: "humble"

    - name: ROS CI Build
      uses: ros-tooling/action-ros-ci@v0.3
      with:
        # package-name: "rosa"
        target-ros2-distro: "humble"
        skip-tests: true

    - name: Import workspace and install dependencies
      run: |
        sudo apt update && sudo apt install -y python3-vcstool python3-rosdep
        mkdir ~/robotx_ws
        # sudo rosdep init
        # rosdep update
        # rosdep install --from-paths ~/ros2_ws/src --ignore-src --rosdistro humble -y

    - name: Check out repository
      uses: actions/checkout@v4
      with:
        # path: robotx_ws/
        
        submodules: 'recursive'

    - name: Build workspace
      run: |
        source /opt/ros/humble/setup.bash
        # cd ~/robotx_ws
        # colcon build
