
name: ROS 2 CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up ROS 2 environment
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble

    - name: Import workspace and install dependencies
      run: |
        sudo apt update && sudo apt install -y python3-vcstool python3-rosdep
        mkdir ~/robotx_ws
        sudo rosdep init
        rosdep update
        # rosdep install --from-paths ~/ros2_ws/src --ignore-src --rosdistro humble -y

    - name: Check out repository
    - uses: actions/checkout@v4
      with:
          path: robotx_ws/
          submodules: 'recursive'

    - name: Build workspace
      run: |
        source /opt/ros/humble/setup.bash
        cd ~/robotx_ws
        colcon build
